DROP TABLE IF EXISTS inventory;
DROP TABLE IF EXISTS classification;
DROP TABLE IF EXISTS account;
DROP TYPE IF EXISTS account_type;

CREATE TYPE account_type AS ENUM ('Client', 'Employee', 'Admin');

CREATE TABLE classification (
    classification_id INT GENERATED BY DEFAULT AS IDENTITY,
    classification_name CHARACTER VARYING NOT NULL,
    PRIMARY KEY (classification_id)
);
-- this will be the inventory table that will store the information about the vehicles in the inventory. The inv_id is the primary key and is generated automatically. The classification_id is a foreign key that references the classification table, which will allow us to categorize the vehicles based on their classification (Custom, Sedan, SUV, Truck). The inv_price is a numeric value with 9 digits and 0 decimal places, which will allow us to store prices up to 999999999.
CREATE TABLE inventory (
    inv_id INT GENERATED BY DEFAULT AS IDENTITY,
    inv_make CHARACTER VARYING NOT NULL,
    inv_model CHARACTER VARYING NOT NULL,
    inv_year CHARACTER(4) NOT NULL,
    inv_description TEXT NOT NULL,
    inv_image CHARACTER VARYING NOT NULL,
    inv_thumbnail CHARACTER VARYING NOT NULL,
    inv_price NUMERIC(9, 0) NOT NULL,
    inv_miles INT NOT NULL,
    inv_color CHARACTER VARYING NOT NULL,
    classification_id INT NOT NULL,
    PRIMARY KEY (inv_id),
    CONSTRAINT fk_classification FOREIGN KEY (classification_id) REFERENCES classification(classification_id)
);
-- The accounts table will store the user information for the application, including their first name, last name, email, password, and account type (Client, Employee, Admin). The account_id is the primary key and is generated automatically. The account_type is an ENUM that restricts the values to 'Client', 'Employee', or 'Admin'.
CREATE TABLE account (
    account_id INT GENERATED BY DEFAULT AS IDENTITY,
    account_firstname CHARACTER VARYING NOT NULL,
    account_lastname CHARACTER VARYING NOT NULL,
    account_email CHARACTER VARYING NOT NULL,
    account_password CHARACTER VARYING NOT NULL,
    account_type account_type NOT NULL DEFAULT 'Client',
    PRIMARY KEY (account_id)
);
-- Inserting the sample of the dataset for the application to work with. This will be used for testing and development purposes.
INSERT INTO classification (classification_name) 
VALUES ('Custom'), ('Sedan'), ('SUV'), ('Truck');

INSERT INTO inventory (inv_make, inv_model, inv_year, inv_description, inv_image, inv_thumbnail, inv_price, inv_miles, inv_color, classification_id)
VALUES 
('Chevrolet', 'Camaro', '2018', 'If you want to jump out of this car and get into another, you''re crazy.', '/images/camaro.jpg', '/images/camaro-tn.jpg', '25000', '45000', 'Silver', 2),
('Batmobile', 'Original', '1966', 'Holy rusted metal, Batman! This is the original Batmobile.', '/images/batmobile.jpg', '/images/batmobile-tn.jpg', '65000', '120000', 'Black', 1),
('DMC', 'Delorean', '1981', 'Where we''re going, we don''t need roads.', '/images/delorean.jpg', '/images/delorean-tn.jpg', '55000', '89000', 'Silver', 1),
('Audi', 'R8', '2020', 'The Audi R8 is a masterpiece of German engineering.', '/images/audi.jpg', '/images/audi-tn.jpg', '120000', '15000', 'Red', 1),
('Ford', 'Mustang', '1969', 'The 1969 Ford Mustang is a true American classic.', '/images/mustang.jpg', '/images/mustang-tn.jpg', '45000', '78000', 'Blue', 2),
('Jeep', 'Wrangler', '2021', 'The Jeep Wrangler is the ultimate off-road vehicle.', '/images/wrangler.jpg', '/images/wrangler-tn.jpg', '35000', '12000', 'Green', 3),
('Ford', 'F-150', '2022', 'The Ford F-150 is America''s best-selling truck.', '/images/f150.jpg', '/images/f150-tn.jpg', '42000', '8000', 'Gray', 4);

INSERT INTO account (account_firstname, account_lastname, account_email, account_password, account_type)
VALUES 
('Tony', 'Stark', 'tony@stark.com', 'Iamironman1', 'Admin'),
('Peter', 'Parker', 'peter@spiderman.com', 'Spidey123', 'Employee'),
('Steve', 'Rogers', 'steve@avengers.com', 'America4ever', 'Client'),
('Natasha', 'Romanoff', 'natasha@avengers.com', 'BlackWidow', 'Client');