-- this is the rebuild.sql file that will drop and recreate the tables, types, and insert the initial data for the inventory management system. It also includes the updates to the inventory descriptions and image paths as specified in Task 1.

DROP TABLE IF EXISTS inventory;
DROP TABLE IF EXISTS classification;
DROP TABLE IF EXISTS account;
DROP TYPE IF EXISTS account_type;

CREATE TYPE account_type AS ENUM ('Client', 'Employee', 'Admin');

CREATE TABLE classification (
    classification_id INT GENERATED BY DEFAULT AS IDENTITY,
    classification_name CHARACTER VARYING NOT NULL,
    PRIMARY KEY (classification_id)
);
--  in this section we create the inventory and account tables with the appropriate columns, data types, and constraints. The inventory table has a foreign key constraint that references the classification table, and the account table has a default value for the account_type column.

CREATE TABLE inventory (
    inv_id INT GENERATED BY DEFAULT AS IDENTITY,
    inv_make CHARACTER VARYING NOT NULL,
    inv_model CHARACTER VARYING NOT NULL,
    inv_year CHARACTER(4) NOT NULL,
    inv_description TEXT NOT NULL,
    inv_image CHARACTER VARYING NOT NULL,
    inv_thumbnail CHARACTER VARYING NOT NULL,
    inv_price NUMERIC(9, 0) NOT NULL,
    inv_miles INT NOT NULL,
    inv_color CHARACTER VARYING NOT NULL,
    classification_id INT NOT NULL,
    PRIMARY KEY (inv_id),
    CONSTRAINT fk_classification FOREIGN KEY (classification_id) REFERENCES classification(classification_id)
);

CREATE TABLE account (
    account_id INT GENERATED BY DEFAULT AS IDENTITY,
    account_firstname CHARACTER VARYING NOT NULL,
    account_lastname CHARACTER VARYING NOT NULL,
    account_email CHARACTER VARYING NOT NULL,
    account_password CHARACTER VARYING NOT NULL,
    account_type account_type NOT NULL DEFAULT 'Client',
    PRIMARY KEY (account_id)
);


--  in this section we insert the initial data into the classification, inventory, and account tables. We also perform the updates to the inventory descriptions and image paths as specified in Task 1.
INSERT INTO classification (classification_name) 
VALUES ('Custom'), ('Sedan'), ('SUV'), ('Truck');

INSERT INTO inventory (inv_make, inv_model, inv_year, inv_description, inv_image, inv_thumbnail, inv_price, inv_miles, inv_color, classification_id)
VALUES 
('Chevrolet', 'Camaro', '2018', 'If you want to jump out of this car and get into another, you''re crazy.', '/images/camaro.jpg', '/images/camaro-tn.jpg', '25000', '45000', 'Silver', 2),
('Batmobile', 'Original', '1966', 'Holy rusted metal, Batman! This is the original Batmobile.', '/images/batmobile.jpg', '/images/batmobile-tn.jpg', '65000', '120000', 'Black', 1),
('DMC', 'Delorean', '1981', 'Where we''re going, we don''t need roads.', '/images/delorean.jpg', '/images/delorean-tn.jpg', '55000', '89000', 'Silver', 1),
('Audi', 'R8', '2020', 'The Audi R8 is a masterpiece of German engineering.', '/images/audi.jpg', '/images/audi-tn.jpg', '120000', '15000', 'Red', 1),
('Ford', 'Mustang', '1969', 'The 1969 Ford Mustang is a true American classic.', '/images/mustang.jpg', '/images/mustang-tn.jpg', '45000', '78000', 'Blue', 2),
('Jeep', 'Wrangler', '2021', 'The Jeep Wrangler is the ultimate off-road vehicle.', '/images/wrangler.jpg', '/images/wrangler-tn.jpg', '35000', '12000', 'Green', 3),
('Ford', 'F-150', '2022', 'The Ford F-150 is America''s best-selling truck.', '/images/f150.jpg', '/images/f150-tn.jpg', '42000', '8000', 'Gray', 4);

INSERT INTO account (account_firstname, account_lastname, account_email, account_password, account_type)
VALUES 
('Tony', 'Stark', 'tony@stark.com', 'Iamironman1', 'Admin'),
('Peter', 'Parker', 'peter@spiderman.com', 'Spidey123', 'Employee'),
('Steve', 'Rogers', 'steve@avengers.com', 'America4ever', 'Client'),
('Natasha', 'Romanoff', 'natasha@avengers.com', 'BlackWidow', 'Client');

-- Query 4 from Task 1 (modify description)
UPDATE inventory 
SET inv_description = REPLACE(inv_description, 'small interiors', 'a huge interior') 
WHERE inv_make = 'GM' AND inv_model = 'Hummer';

-- Query 6 from Task 1 (update image paths)
UPDATE inventory 
SET 
    inv_image = REPLACE(inv_image, '/images/', '/images/vehicles/'),
    inv_thumbnail = REPLACE(inv_thumbnail, '/images/', '/images/vehicles/');